### ISSUE TITLE
Dark mode on v1.11.3 is not working

### ISSUE THREAD

**Issue by mehdichaouch** [DataTables/Dist-DataTables-Bootstrap5#9]
Hello,

I hope to not open this issue for nothing, but after many tests, it seems that the dark mode doesn't use the recommendation of Bootstrap.

To use the dark mode, there is a pretty simple [doc](https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode).
> [Just] add `data-bs-theme="light"` or `data-bs-theme="dark"` to the parent

the highest element is `html`, same workflow as Bootstrap doc page.

Bootstrap shared this [JS script](https://getbootstrap.com/docs/5.3/customize/color-modes/#javascript) to make the implementation easy.

The problem (imo) is the implementation with `html.dark` in the [file](https://github.com/DataTables/Dist-DataTables-Bootstrap5/blob/master/css/dataTables.bootstrap5.css#L28) is not correct.

It should be in:
```css
[data-bs-theme="dark"] {
  table.dataTable td.dt-control:before {
    color: rgba(255, 255, 255, 0.5);
  }
  table.dataTable tr.dt-hasChild td.dt-control:before {
    color: rgba(255, 255, 255, 0.5);
  }
}
```

The demo page [DataTables example - Bootstrap 5 styling](https://datatables.net/extensions/responsive/examples/styling/bootstrap5.html) is working, because you have this snippet hack of [JS code](https://datatables.net/media/js/mode.js):

```css
if (mode === 'dark') {
	var html = document.getElementsByTagName('html')[0];

	html.className += html.className + ' dark';
	html.setAttribute('data-bs-theme', 'dark');
}
```

Is it possible to implement dark mode properly?

Best,
